package com.onlineeducation.entity;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * null
 * @TableName user
 */
@Data
public class User implements Serializable {
    /**
     * 用户ID
     *
     * @mbg.generated 2021-01-27 17:52:01
     */
    private Integer userId;

    /**
     * 角色类型
     *
     * @mbg.generated 2021-01-27 17:52:01
     */
    private Integer userRole;

    /**
     * 用户名
     *
     * @mbg.generated 2021-01-27 17:52:01
     */
    private String userName;

    /**
     * 密码
     *
     * @mbg.generated 2021-01-27 17:52:01
     */
    private String password;

    /**
     * 名称
     *
     * @mbg.generated 2021-01-27 17:52:01
     */
    private String realName;

    /**
     * 头像
     *
     * @mbg.generated 2021-01-27 17:52:01
     */
    private String userIcon;

    /**
     * 电话号码
     *
     * @mbg.generated 2021-01-27 17:52:01
     */
    private String phoneNum;

    /**
     * 邮箱
     *
     * @mbg.generated 2021-01-27 17:52:01
     */
    private String email;

    /**
     * 联系地址
     *
     * @mbg.generated 2021-01-27 17:52:01
     */
    private String address;

    /**
     * 状态
     *
     * @mbg.generated 2021-01-27 17:52:01
     */
    private Boolean deleteFlag;

    /**
     * 创建时间
     *
     * @mbg.generated 2021-01-27 17:52:01
     */
    private Date createTime;

    /**
     * 修改时间
     *
     * @mbg.generated 2021-01-27 17:52:01
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated 2021-01-27 17:52:01
     */
    private static final long serialVersionUID = 1L;
}